version: '3'
services:
  cerberus:
    image: registry.rlab.be/seykron/patobot:1.1.0
    restart: unless-stopped
    depends_on:
      - h2
    tmpfs:
      - /tmp
    environment:
      - telegram_access_token
      - slack_access_token
      - airtable_access_token
      - airtable_app_id
      - db_url
      - db_driver
      - db_user
      - db_password
  h2:
    image: "oscarfonts/h2"
    restart: unless-stopped
    volumes:
      - ./patobot-db/patobot:/opt/h2-data:rw
